baseURL = 'https://cubiclecore.github.io/DoodzV3_blog/'
footnoteReturnLinkContents = ""
languageCode = 'en-us'
title = 'Cubicle Core Blog'
#theme = "bootstrap" 
theme = "ananke"

MetaDataFormat = "yaml"
DefaultContentLanguage = "en"
SectionPagesMenu = "main"
Paginate = 15 # this is set low for demonstrating with dummy content. Set to a higher number
googleAnalytics = ""
enableRobotsTXT = true

[params]
    AuthorName = "Connor Ruppert"
    background_color_class = "bg-black"
    featured_image = "/images/cbxcr_hugo.png"
    recent_posts_number = 2
    logo = "/images/cbxcr_eqtst.png"
    facebook = ""
    twitter = ""
    instagram = ""
    youtube = ""
    github = ""
    gitlab = ""
    linkedin = ""